# GitLab user. git by default
user: git

# URL to GitLab instance, used for API calls. Default: http://localhost:8080.
gitlab_url: https://gitlab.dev.local

# See installation.md#using-https for additional HTTPS configuration details.
http_settings:
    #  read_timeout: 300
    #  user: someone
    #  password: somepass
    #  ca_file: /etc/ssl/cert.pem
    #  ca_path: /etc/pki/tls/certs
    self_signed_cert: true

auth_file: "/home/git/.ssh/authorized_keys"

# Redis settings used for pushing commit notices to gitlab
redis:
    bin: "/usr/bin/redis-cli"
    # host: 127.0.0.1
    # port: 6379
    # pass: redispass # Allows you to specify the password for Redis
    database: 0
    socket: "/var/run/redis/redis.sock"
    namespace: resque:gitlab
log_level: INFO

# Audit usernames.
# Set to true to see real usernames in the logs instead of key ids, which is easier to follow, but
# incurs an extra API call on every gitlab-shell command.
audit_usernames: true

# Log file.
# Default is gitlab-shell.log in the root directory.
# log_file: "/home/git/gitlab-shell/gitlab-shell.log"

# Log level. INFO by default
log_level: INFO

# Git trace log file.
# If set, git commands receive GIT_TRACE* environment variables
# See https://git-scm.com/book/es/v2/Git-Internals-Environment-Variables#Debugging for documentation
# An absolute path starting with / – the trace output will be appended to that file.
# It needs to exist so we can check permissions and avoid to throwing warnings to the users.
git_trace_log_file:
